// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApi.Models;

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            //modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                //{
                //    b.Property<long>("Id")
                //        .ValueGeneratedOnAdd();

                //    b.Property<bool>("IsComplete");

                //    b.Property<string>("Name");

                //    b.HasKey("Id");

                //    b.ToTable("TodoItems");
                //});
            modelBuilder.Entity("TodoApi.Models.Post", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<long>("UserId");

                b.Property<string>("Content");
                b.Property<System.DateTime>("CreatedOn");

                b.HasKey("Id");

                b.ToTable("Posts");
            });
            modelBuilder.Entity("TodoApi.Models.User", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Username");

                b.Property<string>("Email");
                b.Property<string>("Password");

                b.HasKey("Id");

                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
